manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: WSTRN
      url-base: https://github.com/WSTRN
  projects:
    - name: zmk
      remote: WSTRN
      revision: main
      import: app/west.yml
  self:
    path: config
